### PR TITLE
(feat) added overlay for login and some css fixes [closes #104]

### LINKED ISSUE #104: add login overlay

### PR DESCRIPTION
**Pull request by bcjl**
Still need user interactivity, but can be hard code toggled. Test are passing.

### CODE REVIEW

**Comment by kurtbartholomew** [comment]
:+1:

**Comment by bcjl** [comment]
I have :grapes: expectations for this feature

**Comment by lugyin** [comment]
:g

**Comment by kurtbartholomew** [comment]
:gb:

**Pull request merged**
